name: cpp-linter

on:
  push:

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run C++ linter
        uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: ''
          files-changed-only: false
          thread-comments: false

      - name: Check linter results
        if: steps.linter.outputs.checks-failed != 0
        run: |
          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
          exit 1
