name: Clang Tidy

on:
  push:
  pull_request:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy
      
      - name: Run clang-tidy (Warnings are suggestions)
        run: |
          find . -type f \( -name "*.cpp" -o -name "*.cc" -o -name "*.cxx" \) \
            -exec clang-tidy {} \
            --checks='bugprone-*,performance-*,readability-*,modernize-*' \
            --warnings-as-errors='*' \
            -- -std=c++17 \;